spring.application.name=todo
server.port=3000
storage=entity
# PostgreSQL Database Configuration (Aiven)
spring.datasource.url=jdbc:postgresql://pg-4c03245-taskmanagement-2025.k.aivencloud.com:13213/defaultdb?sslmode=require
spring.datasource.username=avnadmin

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pooling (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
